### ISSUE TITLE
Add option for single-isolate

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/flutter-connector#4]
> Add an option to not spawn a new isolate on every new message, but instead re-use the existing main isolate

> I think fixing this would also fix #3. I'll try to get it working.

(original: https://github.com/karmanyaahm/flutter_unified_push/issues/6)

**Comment by p1gp1g** [comment]
It should be fixed now. It uses the main isolate until the app is destroyed and then goes to a new callback isolate
