### ISSUE TITLE
Can't send arbitrary bytes

### ISSUE THREAD

**Issue by emersion** [UnifiedPush/flutter-connector#64]
It seems like this library assume that the incoming messages are valid UTF-8 characters. However it doesn't seem like the [spec](https://unifiedpush.org/spec/server/) requires this: any byte sequence should be passed through to the user.

My use-case is sending encrypted payloads via UP. Right now parts of the payload are replaced with the UTF-8 replacement character (65533), which breaks my decryption logic. I'd rather not use a layer of base64 encoding since this would deviate from the Web Push specification and require an additional HTTP proxy.

**Comment by emersion** [comment]
Ah, it seems like this was a planned changed anyways: https://github.com/UnifiedPush/flutter-connector/pull/56#issuecomment-1016206549

**Comment by p1gp1g** [comment]
We have just released a new spec for android and a new library version to address this problem. We are on a new flutter-connector version too (https://github.com/UnifiedPush/flutter-connector/tree/platform-interface).

The last thing to do is how the flutter lib passes platform specific features requests.

**Comment by emersion** [comment]
I've updated android-connector to v2.0.0 in this branch, if that helps:

https://github.com/emersion/flutter-connector/commits/platform-interface

**Comment by karmanyaahm** [comment]
I think v4.0.0 fixes this?
