### ISSUE TITLE
RegisterAppWithDialog should have ignore option

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/flutter-connector#74]
https://toot.martyn.berlin/@martyn/108520436299324159

> martyn@toot.martyn.berlin - @ Tusky One piece of feedback though is that the fallback should be "quieter". Every time I open tusky after not using it for a while I get a pop-up for "No distributor found". "I know that, I haven't made a decision yet, so please don't bug me" isn't an option ;-)

Idk how this could be achieved without the app having a setting to clear it, though

Also opening a android-connector issue since the concept applies to both

**Comment by p1gp1g** [comment]
Fixed with 4.0.1
