### ISSUE TITLE
Consider returning a nullable string in getDistributor()

### ISSUE THREAD

**Issue by emersion** [UnifiedPush/flutter-connector#88]
Currently the function returns a `Future<String>`, with a special-case of the empty string meaning "no distributor". This is unidiomatic Dart. It would be nicer to change it to `Future<String?>`, with null meaning "no distributor".

**Comment by karmanyaahm** [comment]
@p1gp1g Would this require incrementing the major version?

**Comment by p1gp1g** [comment]
Yes probably. I can revert the change and keep it in suspend
