### ISSUE TITLE
NullPointerException in onMethodCall()

### ISSUE THREAD

**Issue by emersion** [UnifiedPush/flutter-connector#93]
I get this sometimes:

<details>

![Screenshot_20221026-172420](https://user-images.githubusercontent.com/506932/198068365-c8c14672-2a15-4241-b47d-1bf81c17aa92.png)

</details>

My guess is that it's due to `mActivity!!`. Maybe we could add a fallback for `mContext` when `mActivity` is null?

**Comment by p1gp1g** [comment]
Do you when when it happens ? To check if the fallback is enough. We can definitely add this

**Comment by emersion** [comment]
It seems to happen when my app isn't running in the foreground, and its `main()` function gets called after a push message is received.

**Comment by emersion** [comment]
BTW do we really need the activity context here? Since the Android distributor selection dialog is never used (it's implemented via Flutter widgets), can't we always use `mContext`?

**Comment by p1gp1g** [comment]
What is the version of flutter-connector used by your app ?

**Comment by p1gp1g** [comment]
> BTW do we really need the activity context here? Since the Android distributor selection dialog is never used (it's implemented via Flutter widgets), can't we always use `mContext`?

We can test that. The lib did use dialog on android side but not anymore indeed.

**Comment by emersion** [comment]
```
> flutter pub deps | grep unifiedpush
|-- unifiedpush 4.0.2
|   |-- unifiedpush_android 1.1.0
|   |   '-- unifiedpush_platform_interface...
|   '-- unifiedpush_platform_interface 1.0.0
```
