### ISSUE TITLE
Is OnBackgroundHandler supported?

### ISSUE THREAD

**Issue by hatemragab** [UnifiedPush/flutter-connector#97]
I need to send silent notifications
Which contains only payload
And not displaying notifications
Let Clint decide what to do ?

**Comment by p1gp1g** [comment]
The library does not display any notification by itself. You can do whatever you want with the message received, and handled by onMessage

**Comment by p1gp1g** [comment]
I'm closing this issue since the library already allow to achieve what you want to do. This can be reopened if needed
